#!/usr/bin/env python
#
# unix2ctime
#
# Read from stdin and write to stdout, converting any Unix timestamps (see
# regex) to human-readable timestamps.
#

import sys
import re
import time

re_datestamp = re.compile(r"[0-9]{10}\.[0-9]+")

for line in sys.stdin.readlines():
    m = re_datestamp.search(line)
    if m is not None:
        (a, b) = m.span()
        timestamp = time.ctime(float(line[a:b]))
        print("{}{}{}".format(line[:a], timestamp, line[b:].rstrip()))
    else:
        print(line.rstrip())



